### ISSUE TITLE
使用 will-change 优化页面滚动

### ISSUE THREAD

**Issue by chanshiyucx** [chanshiyucx/blog#2]
![cover](https://dn-coding-net-production-pp.qbox.me/f32ed0b0-fc7a-45cf-80c1-52f9e82f56be.jpg)

最近魔改了 [NexT](http://theme-next.iissnan.com/getting-started.html) 主题，加了许多莫名其妙的东西，可能是改得有点太狠了，感觉页面滚动的时候有点卡卡的，emmmm肯定是哪里出了问题，不过没找到解决方法就算了。后面就想试试能不能用纯 CSS 实现动态背景, 毕竟一图流还是太单调，然后意外翻到这个东西~

# 调整背景图片
嘛，废话不说，先看看调整后的背景样式。
调整前：
```css
body {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: top right;
  background-size: cover;
  background-attachment: fixed;
}
```
调整后：
```css
body::before {
  content: '';
  position: fixed;  /* 代替 background-attachment */
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  will-change: transform;   /* 加入 will-change */
  z-index: -1;
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: top right;
  background-size: cover;
}
```

对比会发现只做了三点调整：
1. 将背景图由原来的 `body` 元素调整到了 `::before` 伪元素；
2. 使用 `position: fixed` 代替 `background-attachment: fixed`；
3. 使用 `will-change` 属性；

调整前后性能对比：
调整前：
![调整前](https://dn-coding-net-production-pp.qbox.me/fd940fc1-286f-4fb0-854c-0ac603c47ff0.png)

调整后：
![调整后](https://dn-coding-net-production-pp.qbox.me/5bb2ca61-fda8-4db1-9ff2-593d4070b165.png)

图中两个曲线图，上面是帧数 FPS 下面是内存 CPU 占用，发现帧数确实提升了一截（不是非常肯定、认定、确定是优化后的效果，万一真的只是运气好而已呢:）。

# background-attachment
CSS属性 `background-attachment` 会导致页面重绘，在 Safari 浏览器上已被禁用。至于原因 Stack Overflow 上有说到：
> [Fixed-backgrounds have huge repaint cost and decimate scrolling performance, which is, I believe, why it was disabled.](https://stackoverflow.com/questions/19045364/fixed-body-background-scrolls-with-the-page-on-ios7)

所以使用 `position: fixed` 代替 `background-attachment: fixed` 避免了重绘。

# will-change
CSS属性 `will-change` 可以提前启用 GPU 加速，优化页面的滚动。

当页面滚动触发大面积绘制的时候，浏览器往往是没有准备的，只能被动使用 CPU 去计算与重绘，由于没有准备无法应付大量渲染，于是出现掉帧和卡顿，而 `will-change` 则会在行为触发之前告知浏览器，让浏览器做好准备处理接下来的绘制。

`will-change` 属性值有 `auto`、`scroll-position`、`contents`、`transform`、`opacity`、`left, top`、`unset`、`initial`、`inherit`。一般常用为 `transform`。具体各属性值效果可以查阅 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/will-change)。

> PS：在 Safari 浏览器上，即使设置了 `background-size: cover;`，背景图也会填充到整个文档容器而不是窗口，就会把背景图扩展到非常大，只能看到一个角。调整后直接就修复了这个问题，可谓是一举两得。

Just enjoy it ฅ●ω●ฅ

参考文章：
[<i class="fa fa-link" aria-hidden="true"></i> 使用CSS3 will-change提高页面滚动、动画等渲染性能](http://www.zhangxinxu.com/wordpress/2015/11/css3-will-change-improve-paint/)
[<i class="fa fa-link" aria-hidden="true"></i> Fix scrolling performance with CSS will-change property](https://www.fourkitchens.com/blog/article/fix-scrolling-performance-css-will-change-property/)
